// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace Application
{
	public partial class CustomerViewController : UIViewController
	{
		public CustomerViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
